### ISSUE TITLE
Update demo to recent MDC Web demo

### ISSUE THREAD

**Issue by aforemny** [aforemny/elm-mdc#100]
The MDC Web demo got a complete overhaul after version v0.30.0. Our demo is still based on that version. I would like our demo to be on-par with the upstream MDC Web demo.

This would involve comparing the two demos and updating or rewriting our demo pages to match the HTML and CSS of the upstream demo.

This would be a fairly-large, but completely actionable task for anybody looking for a beginner friendly issue. It would be a great opportunity for anybody looking to familiarize with this library as it will involve writing example code for every component that we have.

Resources:
- [Upstream MDC Web demo](https://material-components.github.io/material-components-web-catalog)
- [Our demo](https://aforemny.github.io/elm-mdc)

Progress:
- [x] Start page a770531ca71bba417c61680b7bb8bf4c4b4fbd9f
- [x] Button 47398cf5f88690232539d322c3f3e534566b2b77
- [x] Card 4553926b32bf360c0fdd394c426a0210a1ac4a3d
- [x] Checkbox 03c187ab550f7e56a4c2839b37709dde87483e0d
- [x] Chips  ee32018c1d046760ffd2d46639000cd6aa1f73f5
- [x] Dialog 48eb56a3161c7ed49a41217dbf05d6095f29c26e
- [x] Drawer
- [x] Elevation  5b39ae87d6fb288580ff7ad0394a74de25b9d786
- [x] FAB  5f0af2efe7e978f313308fb8e4ea277fb76e5e60
- [x] Icon button  19b7786e67269cc72d97424143bfcf1208b52c74
- [x] Image list  6aafa15ffe4c1f12a2198ad31a0b3ed6f236b8bb
- [x] Layout grid  b2041db5d7fde75fcdd347a50e1dcf9e8491d05a
- [x] List
- [x] Linear progress  cd3520700b47e4f9fd45f30deec901ea6675f6b7
- [x] Menu  a88039c8bf97a14a90e237c0ab919fc9afd49ec5
- [x] Radio  6dfeccf7afbb2e54df1929084d3340e1aafb2114
- [x] Ripple  4e62bde9b9cfbe1272870acdcfce986a2ec819c6
- [x] Select f7e5a34a9184318da7c8b70430a20d0a4ededaa2
- [x] Slider 39abbef359730bb91a686701b3cbc6f4511fca88
- [x] Snackbar 9162715b34c23bfd71ce037a65a2837d1f74968d
- [x] Switch 9218ee724deab6cc08aff190068f3551979b0904
- [x] Tabs
- [x] Text field 3a9efefada1911b82edadb3fb2cd0dfd15fd64ca
- [x] Theme f0d750ae663e3c670ae4a3f57e921fe5a9c4bc42
- [x] Top app bar 436c6165caa6031e79869af11c68bb2c4cd3f9e8
- [x] Typography 6e8460aa97b437abbbbc75af0304797d6432c7c0

**Comment by SidneyNemzer** [comment]
Looks like the MDC demo has nifty SVGs for each component. How would you like those to be handled? Use theirs? Use our own images? Something else?

**Comment by aforemny** [comment]
I would suggest to use their images/ svg files.

**Comment by SidneyNemzer** [comment]
Sounds good. Personally I won't have time to work on this right now, but I might in the near future if no one else does.

**Comment by isomoar** [comment]
I would like to update `Startpage` with new svg files.

**Comment by Montycarlo** [comment]
PR #114 for Typography - had to update the Typography implementation

**Comment by aforemny** [comment]
I will be working on this in the master-0.38.2 branch. I plan that that will become the new master soon.

**Comment by berenddeboer** [comment]
As part of the 0.42.1 upgrade I'm attempting I'll be reworking the demos a bit to move them more towards the new ones.
