### ISSUE TITLE
Textfield clears when value is not given if value previously was given

### ISSUE THREAD

**Issue by sproctor** [aforemny/elm-mdc#106]
There may be a better way to do this that is not obvious to me.

I'm to create a textfield that is backed by a Maybe Int in the model. If the user types in an invalid number, I want the variable to be Nothing and display an error message and let the user correct their error, but leave the contents of the textfield as they were typed..

What happens is when the user enters a letter, for instance, I set my value to Nothing, I stop setting Textfield.value in the TextField options, and the Textfield shows up blank. From there on, the user can type whatever invalid values I want and they aren't cleared.

I believe that if Textfield.value is not set, then the contents of the textfield should be left even if Textfield.value had been previously set.

**Comment by aforemny** [comment]
Hi @sproctor, thank you for reporting this. I agree that text field's behavior should be as you suggest. I will try to implement it that way one I find the time.

**Comment by aforemny** [comment]
Hi @sproctor, I finally found the time to follow up on that. However, looking [at this Ellie](https://ellie-app.com/LftJY3B2xpa1) it seems the issue you describe is also present in Elm's html library, correct?

Generally looking at your use-case, I found it easier to store in my model:
`{ …, intAsTyped : String, intConverted : Maybe Int }`

and then do in `update`:
```
InputInt string ->
    { model | intAsTyped = string, intConverted = Result.toMaybe (String.toInt string) }
```

With that approach, you could set `Textfield.value` all the time, not running into the issue you are describing.

**Comment by sproctor** [comment]
Sorry, I'm new to Elm and this one seemed really counter-intuitive to me. It still does, but it would be worse to be different from other Elm inputs. Thanks so much for your help!

**Comment by wscherphof** [comment]
It seems to me this actually is an issue. I think I'll report a new one, stated as a feature request.
