### ISSUE TITLE
Ripple Fade-off

### ISSUE THREAD

**Issue by Montycarlo** [aforemny/elm-mdc#113]
There is a problem with the fade-off for Ripples.

The elm-mdc's ripple effect does not fade-out back to the original primary colour of the component.

Material Components Ripple
![material-button](https://user-images.githubusercontent.com/1904543/43518171-8734c170-95ce-11e8-90c9-1b0126389874.gif)
https://material-components.github.io/material-components-web-catalog/#/component/button

elm-mdc's Ripple
![mdc-button](https://user-images.githubusercontent.com/1904543/43518173-88046a10-95ce-11e8-80b8-ee136b227e52.gif)
https://aforemny.github.io/elm-mdc/#buttons

**Comment by aforemny** [comment]
Nice catch! Thank you for reporting this. :-)

**Comment by berenddeboer** [comment]
I can't see this with [the official demo](https://material-components.github.io/material-components-web-catalog/#/component/button) the color is not changed back to primary until the focus leaves.

What am I missing?

**Comment by aforemny** [comment]
@berenddeboer Last time I checked, I also did not understand anymore what the issue was here. Let's close this? @Montycarlo Feel free to reopen if that issue persists in the current demo.

**Comment by SidneyNemzer** [comment]
I think I see the issue: The Material Components ripple fades as it expands. The elm-mdc ripple expands, then disappears with no fade. It's pretty subtle though, I wish I could step through the GIFs frame-by-frame.

**Comment by SidneyNemzer** [comment]
Actually, in the current elm-mdc demo, the ripple correctly fades as it expands. So maybe no longer an issue.
