### ISSUE TITLE
Elm 0.19

### ISSUE THREAD

**Issue by dpinn** [aforemny/elm-mdc#115]
What are your thoughts on migration to Elm 0.19 for elm-mdc? Is it something you'd consider? If so, what timeframe do you have in mind?

Thank you very much for your very valuable contribution to the Elm ecosystem.

**Comment by aforemny** [comment]
Hi David, thank you for raising this question. I plan to update elm-mdc to Elm 0.19.
I hope I will get to that within the next month.

**Comment by aforemny** [comment]
Closing this in favor of #116.
