### ISSUE TITLE
Tabs indicator too long

### ISSUE THREAD

**Issue by dpinn** [aforemny/elm-mdc#117]
The indicator on my tabs is being improperly sized (see image). Perhaps it's the scale that is not calculated correctly. As I search for the cause, can you give me any hints or hunches about what the problem might be?

<img width="228" alt="indicator" src="https://user-images.githubusercontent.com/724936/44944504-9f9cbf00-ae1b-11e8-89f0-85e9edfffa7b.png">

My own early hunch is that perhaps it has something to do with the dynamic re-sizing of the iFrame contents using [iFrameResizer](https://github.com/davidjbradshaw/iframe-resizer).

**Comment by dpinn** [comment]
I have found the bug that causes this problem. Should create a pull request from a fork, or will you let me push a topic branch to the elm-mdc repository?  @aforemny

**Comment by aforemny** [comment]
Hi @dpinn, thank you for looking into that. Your proposed fix is exactly right.
