### ISSUE TITLE
Using elm-mdc with webpack

### ISSUE THREAD

**Issue by AllanWang** [aforemny/elm-mdc#127]
I'm trying to get webpack set up, in part because modifying the web component styles requires it.

Is there anything special in this project when it comes to generating the css file? If we replace it with the one directly in web components, would that work too?

**Comment by aforemny** [comment]
Hi @AllanWang, you do not need webpack to modify material-web-component's styling. You can include their SASS files, and generate your CSS from that. I frequently include it like so inside my main SASS file (all imports are coming from the respective NPM packages):

```
@import "normalize.css";

$roboto-font-path: 'fonts';
@import "roboto-fontface/css/roboto/sass/roboto-fontface";

$mdc-theme-primary: #000;
$mdc-theme-secondary: #f00;
$mdc-theme-background: #fff;
@import "@material/theme/mdc-theme";

@import "@material/button/mdc-button";
// etc.
// import all components you need
```

There should be nothing special. If you are having trouble getting it to work with webpack, would you have a link to a repository that I can try?

**Comment by AllanWang** [comment]
The solution was to have my own sass watcher, and to include the paths of elm-mdc's node_modules. You can also use `npm-run-all` so that you start both the watcher and `elm-app start` at the same time.
