### ISSUE TITLE
[Question] Having both leading and trailing textfield icons

### ISSUE THREAD

**Issue by AllanWang** [aforemny/elm-mdc#128]
Is there a reason why having both leading and trailing textfield icons is not allowed in this library?

From the [docs](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield/icon), it looks like it is permitted, yet the implementation seems to disable it:

```elm
cs "mdc-text-field--with-leading-icon"
|> when ((config.leadingIcon /= Nothing) && (config.trailingIcon == Nothing))
```

The [usage of either icons](https://github.com/aforemny/elm-mdc/blob/elm-19/src/Internal/Textfield/Implementation.elm#L482) when generating the element also produces a bug in that if both leading and trailing is defined, the leading icon will be used at the end of the field

**Comment by aforemny** [comment]
Hi @AllanWang, thanks for reporting this. Support for leading and trailing icons are a bit limited right now.  In particular, I think event handlers are not supported yet. I will look into that and come up with something better. Will have to check if both leading and trailing icons are supported upstream, because I don't know. :-)

**Comment by AllanWang** [comment]
I'm still new to elm, but I will like to help out if possible. From the demos shown in the official mdc, they don't showcase event handlers either. Style wise, the links from the docs show that it is supported

**Comment by wscherphof** [comment]
Also, text overlaps icon (0.19)
![afbeelding](https://user-images.githubusercontent.com/665662/46996669-c8ec8280-d11d-11e8-8367-3bc716abab4b.png)

**Comment by berenddeboer** [comment]
Support for this has now been added to [the 0.42 branch](https://github.com/aforemny/elm-mdc/pull/148).
