### ISSUE TITLE
Textfield.outlined 0.19: outline is off

### ISSUE THREAD

**Issue by wscherphof** [aforemny/elm-mdc#131]
![afbeelding](https://user-images.githubusercontent.com/665662/46910227-1790f580-cf41-11e8-8e2c-42b9b31412c6.png)

**Comment by wscherphof** [comment]
Ok, create-elm-app's default styleswere messing with this as well.

Still, I found this specific problem: the outline fails as soon as you set a `Textfield.value`:
![afbeelding](https://user-images.githubusercontent.com/665662/48120506-96442e80-e272-11e8-8657-022e1145ede0.png)
On Focus it works:
![afbeelding](https://user-images.githubusercontent.com/665662/48120557-bd9afb80-e272-11e8-863a-7ff69544e904.png)
After Change it works as well, but it consistently fails when setting the value on first view.

**Comment by berenddeboer** [comment]
This is fixed in the 0.42.1 upgrade I'm doing: https://github.com/berenddeboer/elm-mdc/tree/update-to-v0.42.1
