### ISSUE TITLE
TopAppBar expandable search field.

### ISSUE THREAD

**Issue by Natim** [aforemny/elm-mdc#139]
Do you know how it can be possible to add a search field inside the TopAppBar?
Can we make it expandable on click with elm-mdc?

![image](https://user-images.githubusercontent.com/229453/49927598-8eedf180-febe-11e8-8189-74284c7cce65.png)

**Comment by berenddeboer** [comment]
Hi @Natim, apologies for the delay. I think yuou can put any HTML inside a TopAppBar.sections, so I suggest you just put the search field there and see what happens.

Expandable on click: you mean the search field? You probably can attach an event handler to onFocus/onBlur and do some magic there.
