### ISSUE TITLE
Component Ripple

### ISSUE THREAD

**Issue by aforemny** [aforemny/elm-mdc#14]
**Component:**
- [x] CSS components
- [x] JS components
- [x] Demo

**Bugs:**
- [ ] CSS support is unchecked
- [ ] CSS variable support is missing upstream
- [ ] Add user-facing function `rippleSurface`

**Comment by kirchner** [comment]
The ripple effect does not seem to work (it is very short) when just tapping a touchpad (rather then really clicking).  (Under chrome and firefox on macos)

**Comment by aforemny** [comment]
This should be fixed with b57e2e53f7608cb0ded4f2052117c5426abd77ac. Thanks for reporting!

**Comment by aforemny** [comment]
Internal Ripple applications cannot set `mdc-ripple-surface`, so there should be a user-facing `rippleSurface`.
