### ISSUE TITLE
Table demos

### ISSUE THREAD

**Issue by Natim** [aforemny/elm-mdc#140]
Do you have a demo for tables similar to https://material-ui.com/demos/tables/?

**Comment by berenddeboer** [comment]
Note that this is Material UI, which is a completely different library. It is a Material Design implementation for React. Elm-mdc is based upon Google's own implementation of Material Design.

**Comment by Natim** [comment]
My understanding is that Material UI is using the Material Design implementation to implement some bigger components (using the framework). I am pretty sure we could use elm-mdc to implement the same kind of tables. However it is probably a bunch of work to make it happen.
That's why I wanted to know if anyone did already.
