### ISSUE TITLE
TopAppBar.actionItem causes full page reload

### ISSUE THREAD

**Issue by wscherphof** [aforemny/elm-mdc#142]
When running as `Browser.application`, clicking the `<a>` rendered by TopAppBar.actionItem, causes the full page to reload.

A brittle workaround is to use an `<i>`-rendering Icon with action-item styling instead, like:
```elm
Icon.view
    [ Options.onClick PutVoorziening
    , cs "mdc-top-app-bar__action-item"
    ]
    "send"
```

**Comment by wscherphof** [comment]
Same with TopAppBar.NavigationIcon

**Comment by berenddeboer** [comment]
Hi Wouter, I think this was caused by a missing href="#", have added that.

**Comment by berenddeboer** [comment]
I'm actually not happy with this solution. If you have a "#" your app will still attempt to reroute. And [the example](https://material-components.github.io/material-components-web-catalog/#/component/top-app-bar) actually uses a button with nice ripple effect which we don't have. So I think that's what we need.

**Comment by berenddeboer** [comment]
OK, added the proper method, using buttons. Added ripple support so this is a breaking change unfortunately.

**Comment by wscherphof** [comment]
👍🙏

Op do 25 apr. 2019 om 08:13 schreef Berend de Boer <notifications@github.com
