### ISSUE TITLE
Get rid of Dialog.surface

### ISSUE THREAD

**Issue by berenddeboer** [aforemny/elm-mdc#144]
Do we really need Dialog.surface? I propose we get rid of this, and the dialog immediately takes header, body and footer as its nodes, which are then wrapped with surface.

**Comment by aforemny** [comment]
Hi @berenddeboer, I think we can drop the Dialog.surface as any dialog would use that the expected way. I exposed it, because I wasn't sure if dialogs without a Dialog.backdrop were a use-case. But I am leaning towards that they aren't.
