### ISSUE TITLE
docs for this package

### ISSUE THREAD

**Issue by dgaedcke** [aforemny/elm-mdc#149]
I'm new to both Elm and JS/Webpack.  I've never used either & I'm trying to follow [this tutorial](https://youtu.be/U3pa-rQLSxA?list=PLJbE2Yu2zumBjR9uDes8DBq4algPzZ1qO) which uses an older version of Material.   Although it's out of sync (imports missing etc), it's the closest to beginner docs I can find.  But I don't even know how to get this package installed.   Can anyone recommend docs or links for beginners to help me get up and running??

**Comment by berenddeboer** [comment]
What exactly is the problem? Creating an hello world? See the `examples` directory, which you could simply copy and start modifying.

**Comment by dgaedcke** [comment]
I don't understand the installation instructions ... it seems very different than other Elm packages.  And of course I'm having trouble mapping new types & methods to that tutorial but that's not on you.  Thanks for building this!!

**Comment by berenddeboer** [comment]
Yes, you can't use 'elm install'. But just look at the examples/hello-world. So clone this library with git, in the directory you want to work with, then add it to the `sources-directories` in your `elm.json` for example simply `"source-directories": [".", "elm-mdc"]`.

Please continue to post the issues here you are having, I'll update the docs so for the next user it should be easier.

**Comment by dgaedcke** [comment]
since the tutorial I'm using (see link above) seems to be the only one "close" to matching your package, you may wish to explain what happened to:

- import Material.Scheme
- import Material.Color

as those seem to be missing now

**Comment by berenddeboer** [comment]
OK, very helpful. To see packages we need you can have a look at `examples/hello-world/elm.json`. But yes, we need a getting started section.

**Comment by dgaedcke** [comment]
Happy to help!!  Appreciate you building this lib & sharing it.   Let me know what else I can do to help and to learn.

I see several other Material projects for Elm that seem inactive or abandoned ... is it reasonable to expect that this will become the preferred/official approach going forward from 0.19?

**Comment by berenddeboer** [comment]
The guy who build this is actually Alexander Foremny. I'm just helping!

The only project I'm aware of that was abandoned was elm-mdl, as this was based on a no longer maintained approach to implement Material Design for the Web. This library depends on the official Google maintained package, so that problem is solved.

If it will be maintained? The more people use it, the more it will be. I.e. I'll work on it as long as I will use it.
