### ISSUE TITLE
elm-mdc.js produces a JavaScript syntax error on IE11

### ISSUE THREAD

**Issue by dpinn** [aforemny/elm-mdc#150]
There are no details yet, and it doesn't happen on MS Edge. I will attempt to narrow down the circumstances and/or the cause, and then post more details here. If anybody else has seen a similar thing, please comment here. I suspect that the slider control is to blame.

**Comment by aforemny** [comment]
Hi @dpinn, I could not reproduce that. Are you using the compiled output of `elm-mdc.js`?

The file `./src/elm-mdc.js` in this repository should be compiled to `./elm-mdc.js`. You can do the compilation by running `webpack --mode production` inside the root directory of this repository, or simple by typing `make`.
