### ISSUE TITLE
Overflowing TabBar does not scroll

### ISSUE THREAD

**Issue by berenddeboer** [aforemny/elm-mdc#158]
It jumps, instead of scroll.

Some earlier notes:

> I think I might be able to animate this too, but I'm having trouble with Json decoding. In decodeGeometry I need to find the .mdc-tab__content class, which I attempted crudely, but the dimensions variable is a Decoder {} so I can't extract the values that way.

> Perhaps I need to do something more complicated? But perhaps there is easy access to the child node, so I'm hoping this is easy for @aforemny.

**Comment by aforemny** [comment]
@berenddeboer Can you post some source code that exhibits that problem? I am not sure if you have problem running a decoder, ie. through event handling, or if you are running into trouble with a `Decoder (Decoder a)` type.

**Comment by berenddeboer** [comment]
Look at the TabBar demo, the "Scrolling tabs" tabs example exhibits the issue: I jump straight to the tab you click on, it doesn't scroll nicely.
