### ISSUE TITLE
Demo improvements and bug fixes

### ISSUE THREAD

**Issue by berenddeboer** [aforemny/elm-mdc#160]
Copied from [closed pull request](https://github.com/aforemny/elm-mdc/pull/148#issuecomment-457961809):

- [x] Demo: Check for unused imports
- [x] Demo: Add Drawer
- [x] Demo: Remove page.hero (deprecated by Hero.view)
- [x] Demo: Remove page.demos (deprecated by Page.demos)
- [x] Demo: Refactor Resources
- [x] Card demo: Use IconButton
- [x] Card demo: Use correct image
- [x] Chip demo: Checkmark is white instead of black
- [x] Fab demo: Add extended FAB examples
- [x] Icon Toggle demo: Use Icon Button
- [x] LayoutGrid demo: Rethink `LayoutGrid.inner` (Cell Alignment demo)
- [x] Ripple demo: Unbounded ripple glitch
- [x] Ripple demo: What's up with class `mdc-ripple-surface`?
- [x] Select demo: Enhanced selects
- [x] Select demo: shapedOutlinedSelect (TODO)
- [x] TabBar demo: Key controls (Left- and RightArrow keys)
- [x] TabBar demo: Scrolling (click on TAB TWO, it should not scroll)
- [x] TextFields demo: Shaped Outlined TextFields
- [x] TextFields demo: Multiline text fields shouldn't specify `TextField.outlined`
- [x] Menu demo: menu opens in top left corner instead near the button as one would expect.

**Comment by cheukwing** [comment]
For me at least, the menu demo now opens in the bottom left corner instead of near the button.

**Comment by berenddeboer** [comment]
> For me at least, the menu (live) demo now opens in the bottom left corner instead of near the button.

Can't repeat this, is this fixed for you now?

**Comment by cheukwing** [comment]
Looks like its been fixed now, might have just been something on my end :smile:

**Comment by berenddeboer** [comment]
The TabBar demo item was more about TabBar missing stuff, so created new issue for that: #253.
