### ISSUE TITLE
Ripple can insert empty style element: can this be removed?

### ISSUE THREAD

**Issue by berenddeboer** [aforemny/elm-mdc#164]
Ripples often create empty style elements. Need to see if this can be removed as I suspect style dom nodes will have some overhead.

**Comment by SidneyNemzer** [comment]
This line creates an obviously empty style node, but it's easy to replace with `text ""`

https://github.com/aforemny/elm-mdc/blob/88efe784920d7aa8cb8a8072bdd88f98a6b7d28f/src/Internal/Ripple/Implementation.elm#L179

**Comment by berenddeboer** [comment]
Yeah, not sure that worked, initial test failed. The real issue as I now understand is that elm doors not allow you to set CSS variables.

**Comment by SidneyNemzer** [comment]
CSS variable support in Elm would be great, but I'm not exactly following how that's related to the *empty* style node? Maybe you could spell it out for me :)

**Comment by berenddeboer** [comment]
Yes we can remove this, [pull request coming in](https://github.com/aforemny/elm-mdc/pull/166)!

@SidneyNemzer: you can now use CSS variables in elm-mdc if you use `styled` and the `css` property!.

The empty style node was something I saw but not really understood. I know understand that elm-mdc emitted a style node to workaround CSS variables being removed.

**Comment by aforemny** [comment]
I thought that the empty style node would be more confusing than having a node appear out of nowhere when the ripple is interacted with. I am however liking the new work-around. Thanks @berenddeboer!

**Comment by berenddeboer** [comment]
Yeah, I suspected something like that, and perhaps the overhead with inserting new style nodes might have been bigger.

I love the new method too, very glad someone suggested this technique! Works very will for elm-mdc as we have our own way of inserting element attributes, so we won't easily clash.
