### ISSUE TITLE
When modal and dismissible drawer open, the mdc-dialog-scroll-lock is added to the body

### ISSUE THREAD

**Issue by berenddeboer** [aforemny/elm-mdc#196]
When you open a modal drawer the mdc-dialog-scroll-lock is added to the body, so any vertical page scrollbar disappears. However, this should happen only for dialogs, not for drawers.

The class is added in `elm-mdc.js`. It does this when the data-focustrap attribute is set, which is set for modal and permissible drawers.

**Comment by SidneyNemzer** [comment]
It adds it for me:

![image](https://user-images.githubusercontent.com/21203108/56449265-e9afb380-62cb-11e9-87fc-34f0539a6950.png)

Not sure if this is related, but you linked to the *drawer* demo!

**Comment by berenddeboer** [comment]
> you linked to the _drawer_ demo

I wrote a totally confusing issue I think. Mind must not be working. Thanks to your comment I now remember the detail as I had looked it in the past. The issue is that this class should only be added for dialogs, never for drawers. But this class is added when you open a drawer too. That's the real bug.

**Comment by berenddeboer** [comment]
I'm thinking the solution might be to explicitly check if the mdc-dialog class is set, and only then add this class.
