### ISSUE TITLE
Component Card

### ISSUE THREAD

**Issue by aforemny** [aforemny/elm-mdc#2]
**Major implementation:**
- [x] CSS components
- [x] Demo

**Comment by kirchner** [comment]
The spacing between the action buttons is too small when compared to upstream. (on chrome and firefox)
![image](https://user-images.githubusercontent.com/3667885/30226464-601581d2-94d6-11e7-9359-6f337fabf184.png)

**Comment by kirchner** [comment]
also the last clicked button does not stay focused
