### ISSUE TITLE
Component Tabs

### ISSUE THREAD

**Issue by aforemny** [aforemny/elm-mdc#20]
**Component:**
- [x] CSS components
- [x] JS components
- [x] Demo

**Bugs:**
- [ ] RTL support

**Comment by kirchner** [comment]
tabs are missing the ripple effect

**Comment by aforemny** [comment]
@kirchner For me it is working. Could you check again? If it still isn't for you, what Browser did you test with?

**Comment by kirchner** [comment]
ok, now it seems to work :)
