### ISSUE TITLE
Tab background ripple does not fade

### ISSUE THREAD

**Issue by mkreisel** [aforemny/elm-mdc#220]
In the tabs component, when a tab is selected the background should ripple to a dark shade, then fade to a lighter background color for the selected tab. This behavior can be observed from the [official MDC tab demo](https://material-components.github.io/material-components-web-catalog/#/component/tabs). However in the elm-mdc tabs component, the darker rippled background does not fade unless you click again outside the tab. At that point it goes to the lighter shade, when it should actually remove all background color. The gif below illustrates the problem and was recorded in Chrome Version 75.0.3770.80 (Official Build) (64-bit) on Ubuntu 18.04. 

![mdc_tab_highlight](https://user-images.githubusercontent.com/7807896/59101218-4ad02c80-88f6-11e9-8eac-3319b6fd1c13.gif)

**Comment by aforemny** [comment]
I am closing this because I am assuming this has been fixed in #219. If the issue persists, please re-open. Thank you both for the report and assistance in solving this!
