### ISSUE TITLE
Positioning of anchored menu

### ISSUE THREAD

**Issue by dpinn** [aforemny/elm-mdc#222]
Should not the anchored menu appear adjacent to the button that triggered its revelation? Compare for example the result of clicking 'OPEN MENU' on these two demos:

https://aforemny.github.io/elm-mdc/#menu

https://material-components.github.io/material-components-web-catalog/#/component/menu

**Comment by aforemny** [comment]
Hi @dpinn, our demo was outdated. I updated the demo. Could you please see if the issue persists?

**Comment by aforemny** [comment]
I am closing this since I think it is solved in current master. If the issue persists, please reopen!
