### ISSUE TITLE
Menu item styling

### ISSUE THREAD

**Issue by dpinn** [aforemny/elm-mdc#227]
I believe that css attributes added to menu items have no effect; for example, adding ```Material.Options.css "padding" "0"``` to a menu item does not remove the padding. Adding ```Material.Options.css "background" "pink"``` does not make the list item pink.

**Comment by aforemny** [comment]
Hi @dpinn, thank you for reporting it. I pushed a fix to master.

**Comment by dpinn** [comment]
Wow, that was quick. Alexander for President.
