### ISSUE TITLE
Button icon placement

### ISSUE THREAD

**Issue by dpinn** [aforemny/elm-mdc#228]
This is a request, not a complaint. The contributors to this library are doing a wonder job. 

I'm after a way to specify that the icon for a button should be placed on the right-hand side rather than the left. 

Blessings.
David

**Comment by aforemny** [comment]
Hi @dpinn,

I added the property `Button.trailingIcon` that should fit your needs (82684688843d4a79cf79cc940ee57b3bd6b1bf7c). I haven't tested it yet, so please let me know if it works for you!

**Comment by dpinn** [comment]
Yes, that works fine. Thanks Alexander.

![add-col](https://user-images.githubusercontent.com/724936/61772924-be8eb000-ae36-11e9-8256-79b774ccdf68.png)

**Comment by aforemny** [comment]
Great. Thanks!
