### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by aforemny** [aforemny/elm-mdc#26]
- [x] Component Typography
- [x] Component Toolbar
- [x] Component Theme
- [x] Component Textfield
- [x] Component Tabs
- [x] Component Switch
- [x] Component Snackbar
- [x] Component Slider
- [x] Component Menu
- [x] Component Select
- [x] Component Ripple
- [x] Component Radio buttons
- [x] Component List
- [x] Component Linear progress
- [x] Component Layout grid
- [x] Component Icon toggle
- [x] Component Grid list
- [x] Component Floating action button
- [x] Component Elevation
- [x] Component Drawer
- [x] Component Dialog
- [x] Component Checkbox
- [x] Component Card
- [x] Component Button

**Comment by mdjnewman** [comment]
Hi @aforemny , happy holidays! I'm keen to try this package out, but it looks like documentation is the big blocker to getting a version published on http://package.elm-lang.org/

I'm fairly new to this library and can't be sure how much time I have to work on it, but let me know if you'd like me to pick up documentation for a few modules.

**Comment by aforemny** [comment]
@mdjnewman Hi! Happy holidays to you too! I would appreciate any help with documentation very much. So if you write up anything let me know! You can contact me on Slack (@aforemny) if you have any questions and/or feedback.

Be advised that cross-browser testing is another big topic in addition to writing documentation. This is definitely not production ready.
