### ISSUE TITLE
Publish demo

### ISSUE THREAD

**Issue by aforemny** [aforemny/elm-mdc#27]
- [x] Component Typography
- [x] Component Toolbar
- [x] Component Theme
- [x] Component Textfield
- [x] Component Tabs
- [x] Component Switch
- [x] Component Snackbar
- [x] Component Slider
- [x] Component Simple menu
- [x] Component Select
- [x] Component Ripple
- [x] Component Radio buttons
- [x] Component List
- [x] Component Linear progress
- [x] Component Layout grid
- [x] Component Icon toggle
- [x] Component Grid list
- [x] Component Floating action button
- [x] Component Elevation
- [x] Component Temporary Drawer
- [x] Component Persistent Drawer
- [x] Component Permanent Drawer above Toolbar
- [x] Component Permanent Drawer below Toolbar
- [x] Component Dialog
- [x] Component Checkbox
- [x] Component Card
- [x] Component Button

**Comment by mdjnewman** [comment]
Have you considered publishing the demo site on each merge to master? I setup something similar for a meet up site a while back - https://github.com/bfpg/talks/blob/master/deploy.sh

Travis builds demo from master & pushes it back to gh-pages branch.

**Comment by aforemny** [comment]
That looks useful! I would like aforemny.github.io/elm-mdc to reflect the latest release, though as to not confuse users. I wouldn't mind setting up something like this in a subdirectory, say aforemny.github.io/elm-mdc/master. Feel free to add that if you would like!

Otherwise I might get around doing that at some point. Anyways thank you for the instructive script! :)
