### ISSUE TITLE
Update TextField value while writing

### ISSUE THREAD

**Issue by Yeboster** [aforemny/elm-mdc#288]
Hello,
First of all thanks for this awesome library, I really love the material components framework and you made a really good implementation.

I'm trying to update the value of a Textfield using `onChange` event and also visualising the result on the same textfield (because I update it using buttons). 
The model:
``` elm
type alias Model =
    { mdc : Material.Model Msg
    , id : Maybe Int
    , note : Maybe Note
    }
```

The partial view:
``` elm
TextField.view Mdc
    "note-id"
    model.mdc
    [ TextField.label "Note Id"
    , TextField.outlined
    , Options.onChange ChangedId
    , TextField.value <|
        case model.id of
            Just id ->
                String.fromInt id

            Nothing ->
                ""
    , TextField.pattern "\\d*"
    , css "margin-right" "4pt"
    ]
    []
, TextField.helperLine
    [ css "align" "center" ]
    [ TextField.helperText
        [ TextField.validationMsg ]
        [ text "Only numbers are accepted" ]
    ]

```

I know it's recursive loop, but the event of the value changing is dispatched and the `onChange` is not triggered.
![event log](https://i.postimg.cc/YScdj78q/Screenshot-2020-06-15-at-16-20-26.png)

What could be the problem ?

**Comment by berenddeboer** [comment]
You will need the `onInput` event. I should add that to the docs actually!
