### ISSUE TITLE
Contrast with Elm Animations

### ISSUE THREAD

**Issue by simonh1000** [aforemny/elm-mdc#29]
This is a somewhat naive suggestion, and apologies if this is well trodden territory, but I tried elm-mdl once and found that tuple update responses created rather a lot of boilerplate, and you are following that same pattern.

More recently I tried [elm-style-animation](http://package.elm-lang.org/packages/mdgriffith/elm-style-animation/3.5.5/Animation) and found it to be much easier to work with. It basically taps into a subscription on requestAnimationFrame and is able to work off of that. For the user, you need to pass the subscription to elm-animation, but not much more than that.

I have not idea whether that would work for material design but wanted to draw it to your attention.

In the same vein, it would be great for the elm community if you could highlight which MDC elements can be used with CSS only - again to get around the challenges of tuple-returning functions in larger apps.

**Comment by aforemny** [comment]
Hi @simonh1000, thank you for your feedback!

To be clear, with tuple update responses you refer to any type signature like this: `update : … -> Msg -> Model -> ( Model, b )`? In attempting to reduce boiler-plate, did you try the regular TEA API (`view`, `update`, …) or the featured render API (`render`, `Material.update`)? The current README.md goes a bit into detail about boiler-plate.

**Comment by aforemny** [comment]
Could you link to elm-animations please so I can take a look at it?

**Comment by simonh1000** [comment]
Yes, I did mean the extra model values that are needed throughout and the code such as 
```
MyButtonMsg msg_ ->
            let
                ( myButton, effects ) =
                    Button.update msg_ model.myButton
            in
                ( { model | myButton = myButton }, Cmd.map MyButtonMsg effects )
```
I can see that the addition of indices helps reduce some the pain.

I do not know whether a different approach would be sufficient to meet all the cases that material design needs to cover, but it would certainly be valuable to learn from the elm-mdl experience

**Comment by aforemny** [comment]
I have no experience with elm-style-animation, so please bear with me:

We are trying to make a parallel between a elm-mdc component and a elm-style-animation Animation, correct? As far as I can tell, both of them expose functions `view`, `Model`, `Msg`, `update`, `subscriptions` and have to be handled in user-code the same way.

The benefit of animations is that an Animation's update returns the updated animation model, in contrast to elm-mdc components which return along a `Cmd m`. This makes component updates more verbose (as you posted), compared to an Animation's update:

    AnimationMsg msg_ ->
        ( { model, style = Animation.update msg_ model.style }, Cmd.none )

Am I understand correct so far?

I have trouble understanding what you mean by
>  For the user, you need to pass the subscription to elm-animation, but not much more than that.

It is my understanding that for each animation, you create a Msg constructor, a field in `Model`, a branch in `update` as well as a `subcription`. This would be the same as with elm-mdc components.
