### ISSUE TITLE
Slider Selection not reflective of mouse position

### ISSUE THREAD

**Issue by Montycarlo** [aforemny/elm-mdc#292]
The 'Slider' component does not work as intended when an ancestor div has `margin-left` style, and offset in other manners.

![Slider Issue](https://user-images.githubusercontent.com/1904543/86114867-7b40c500-bb0e-11ea-8376-59979ea558be.gif)

**Comment by aforemny** [comment]
There was a [fix merged upstream](https://github.com/material-components/material-components-web/pull/5492/files) that I think addresses the same issue.

**Comment by berenddeboer** [comment]
Thanks so much! That fix was not mentioned anywhere in their docs. Let me know if the latest master works better.

**Comment by berenddeboer** [comment]
I was too quick, it actually does not work when the sidebar is open. It seems we need to call getClientBoundingRect to do this stuff correctly.
