### ISSUE TITLE
elm-make says: I cannot find module 'AnimationFrame'. Module 'Material.GridList' is trying to import it.

### ISSUE THREAD

**Issue by metaleap** [aforemny/elm-mdc#31]
I want to play with this promising package, but can't seem to `elm-make` it:

    [00:46 rox ~/g/elm-mdc (master)]$ elm-make
    Some new packages are needed. Here is the upgrade plan.

      Install:
        debois/elm-dom 1.2.3
        elm-lang/core 5.1.1
        elm-lang/dom 1.1.1
        elm-lang/html 2.0.0
        elm-lang/mouse 1.0.1
        elm-lang/svg 2.0.0
        elm-lang/virtual-dom 2.0.4
        elm-lang/window 1.0.1

    Do you approve of this plan? [Y/n] Y
    Starting downloads...

      ● debois/elm-dom 1.2.3
      ● elm-lang/window 1.0.1
      ● elm-lang/html 2.0.0
      ● elm-lang/dom 1.1.1
      ● elm-lang/mouse 1.0.1
      ● elm-lang/virtual-dom 2.0.4
      ● elm-lang/core 5.1.1
      ●
     elm-lang/svg 2.0.0
    Packages configured successfully!
    I cannot find module 'AnimationFrame'.

    Module 'Material.GridList' is trying to import it.

    Potential problems could be:
      * Misspelled the module name
      * Need to add a source directory or new dependency to elm-package.json

**Comment by metaleap** [comment]
OK `elm-lang/animation-frame` was needed in `elm-package.json` --- keeping this issue open in case you want to refresh the json file  =)

**Comment by aforemny** [comment]
I added it in 788c8d0118d475c80976ae5ece5cd0b4dd24a1a6. Thanks!
