### ISSUE TITLE
Slider markers positioned incorrectly

### ISSUE THREAD

**Issue by dpinn** [aforemny/elm-mdc#312]
As you can see in the MP4 file included in the attached zip file, the markers are positioned at the left edge upon initial rendering. On subsequent rendering, they relocate to the correct position. I'm wondering what causes the problem in this case. Could it be that the sliders are being shown in an iFrame?

[20200908_130938.zip](https://github.com/aforemny/elm-mdc/files/5185856/20200908_130938.zip)

BTW, I'm using the latest master branch (Commit 8dc144d, 3 Sep 2020).

**Comment by berenddeboer** [comment]
Looks to me more an issue with not providing the right value initially. iframe shouldn't matter. Any small example that repeats this?

**Comment by dpinn** [comment]
If it was incorrect initial values, then wouldn't the grey bar also be incorrect? As it is, the grey bar is at the correct location, but the marker dot is not.

**Comment by berenddeboer** [comment]
Good point, perhaps because the slider is inactive or so? What if you keep it active/enabled initially, is it wrong then too?

**Comment by dpinn** [comment]
After much poking around, I discovered that it was a problem in the logic of my program, not in elm-mdc. In the read-only state, I wasn't calling Material.update.
