### ISSUE TITLE
Implent the Accordion widget

### ISSUE THREAD

**Issue by charles-dexter-ward** [aforemny/elm-mdc#316]
Hi,

is there any possibility that an Accordion widget will be implemented?

**Comment by aforemny** [comment]
Hi @charles-dexter-ward, this library implements the components of the upstream library [MDC Web](https://github.com/material-components/material-components-web). Therefore, any addition of components here has to first happen at MDC Web.

You might find some information in [their issues](https://github.com/material-components/material-components-web/search?q=accordion&type=issues).
