### ISSUE TITLE
`demo` compiles (but no final output files), but `elm-mdc` alone doesn't

### ISSUE THREAD

**Issue by metaleap** [aforemny/elm-mdc#32]
I guess this repo is heavily work in progress? If so excuse me =) Or am I doing something wrong? `elm-make` "succeeds" ("compiled n modules" --- just no html/js outputs even when using explicit `--output foo` args) when run in the `demo` sub-directory.

But in `elm-mdc`, it doesn't even proceed to compilation, complaining about missing documentation --- annoyingly so, I think this sort of check should be in `elm-package` (for those about to publish) not in `elm-make`, sheesh..

A question, how do you actually transpile+run your own `demo` code-base here?

**Comment by aforemny** [comment]
I just run `make` to build the demo, then run `firefox build/index.html`.

Does that answer your question?

**Comment by metaleap** [comment]
Well don't know what went awry at my end there 3 days ago, but nevermind, already pivoted to PureScript for now  =)
