### ISSUE TITLE
Full-width text fields...well, aren't

### ISSUE THREAD

**Issue by dpinn** [aforemny/elm-mdc#347]
![image](https://user-images.githubusercontent.com/724936/132085576-35800952-3cfd-4f78-883c-2296f795ef18.png)

Tested against commit 713aaa8

**Comment by dpinn** [comment]
Oddly, it renders properly in the online demo; but not with the `elm-mdc.js` and `material-components-web.css` added to the `build` directory.

**Comment by berenddeboer** [comment]
Full width was [removed](https://github.com/material-components/material-components-web/commit/69a35e80ceadb5ef9ffae87345eefbd80b383f51).

Notes say:

> BREAKING_CHANGE: fullwidth variant has been removed since the changes it made were not part of spec.
> To achieve "fullwidth", add width: 100% to the component
