### ISSUE TITLE
Missing installation info / Broken package link

### ISSUE THREAD

**Issue by Pavinati** [aforemny/elm-mdc#43]
So, i was using debois-mdl successfully and i wanted to migrate from mdl to mdc, but it seems this package is not registered in the main elm repository.

Following your link [package documentation](http://package.elm-lang.org/packages/aforemny/elm-mdc/latest)
yelds
> Could not find any versions of package aforemny/elm-mdc

elm-make also gets a bit angry
>> Running "elm:compile" (elm) task
>> Error: Your .elm/packages/ directory may be corrupted. I was led to believe that
>> aforemny/elm-mdc existed, but I could not find anything when I went to look up
>> the published versions of this package.

Am i missing part of your documentation?

**Comment by aforemny** [comment]
Hi @Pavinati, you are not missing anything. It is not released yet.

PS. You might find migrating from elm-mdl a bit difficult, because the set of components is not the same. See [migrating-from-mdl](https://material.io/components/web/docs/migrating-from-mdl/) in Google's documentation.

**Comment by Pavinati** [comment]
@aforemny thanks for your reply.
I'll keep an eye out for any updates!

**Comment by daegren** [comment]
@aforemny Any idea on timeline for this being deployed to packages.elm-lang.org? I'm looking to use this in a project, and would like to not have to add any extra build steps :)

**Comment by aforemny** [comment]
Hi @daegren, unfortunately I do not have an ETA on a release. Roughly, I will have to invest another day or two in finishing the API changes issue, and then it would probably a good idea to catch up with a recent version of MDC Web (0.34.0 currently, if I am not mistaken).

Don't really know how long the second issue would take, and when I do get to doing that. Sorry. :)

**Comment by daegren** [comment]
Not a problem, thanks for your reply!
