### ISSUE TITLE
An upfront question about debugger compatibility

### ISSUE THREAD

**Issue by Spiralis** [aforemny/elm-mdc#44]
Does this library avoid the issues that we see in the [elm-mdl](https://github.com/debois/elm-mdl) library in regards to [breaking the debugger](https://github.com/debois/elm-mdl/issues/318)?

I guess this comes down to whether or not this library is doing this architecturally different in this regard or not.

The reason for asking is that I am considering migrating to use this library instead of [elm-mdl](https://github.com/debois/elm-mdl).

**Comment by aforemny** [comment]
Hi,

it should be possible to make it debugger compatible, but I have not yet done anything to improve the situation from elm-mdl. I will investigate before a release, but until then I do not know for sure.

**Comment by Spiralis** [comment]
Thank you for your reply.

**Comment by aforemny** [comment]
I just checked and elm-mdc is debugger compatible already.

**Comment by Spiralis** [comment]
Excellent. Good to hear :)
