### ISSUE TITLE
Calling "inner" in LayoutGrid's view function.

### ISSUE THREAD

**Issue by fbessou** [aforemny/elm-mdc#48]
According to https://material.io/components/web/catalog/layout-grid/ , a `layout-grid` should always contain a `layout-grid__inner`.
With the current implementation we have to manually call `inner` view in a LayoutGrid's view :
```
  LayoutGrid.view
    []
    [ LayoutGrid.inner
        []
        [ LayoutGrid.Cell
            []
            [ text "..." ]
        ]
    ]
```
Have you considered calling `inner` view directly in the LayoutGrid's view ?
It would allow to write
```
  LayoutGrid.view
    []
    [ LayoutGrid.Cell
        []
        [ text "..." ]
    ]
```

In its current state the "elm-mdc" documentation says that the `inner` view is only needed when nesting a grid into another grid. If we were to keep the current implementation, I think that the documentation should be updated. :)

**Comment by aforemny** [comment]
I guess it makes sense to call LayoutGrid.inner directly from LayoutGrid.view. I added that in 3cb2fe3b762a2bdbc0337df69d72c2f90624355a.

Thank you very much for reporting this!
