### ISSUE TITLE
Component Drawer

### ISSUE THREAD

**Issue by aforemny** [aforemny/elm-mdc#5]
**Component:**
- [x] CSS components
- [x] JS components
- [x] Demo

**Comment by kirchner** [comment]
The header font is not correct. In upstream it does not close after clicking on one of the menu buttons which it does in elm-mdc. Also clicking on the open drawer but not on a button should not close the drawer.

**Comment by aforemny** [comment]
Those issues should be addressed by 620fd8603875f09b32b31ae68b48cad207435516. Thanks a bunch!
