### ISSUE TITLE
List.divider and List.listItem not rendered as <li>

### ISSUE THREAD

**Issue by fbessou** [aforemny/elm-mdc#51]
Several list elements are not rendered as `<li>`, is there a reason for this?
This is the case for `divider` and `listItem` :)

**Comment by aforemny** [comment]
For `<li>` list Items you have `Lists.li`.

The reason for this inconsistency is that I am not sure when one uses `<li>` list items and when `<a>` list items and what divider should be in that case... Ideas?

**Comment by fbessou** [comment]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul) it seems that an `<ul>` element can only contain `<li>` elements, so the `<a>` should probably go into a `<li>` element.

If I read correctly [the divider documentation](https://material.io/components/web/catalog/lists/#list-dividers) the list divider should be a `<li>` with the "separator" role when in a `<ul>` or a `<hr>` when between two `<ul>`.

**Comment by aforemny** [comment]
Thank you for the research!

I plan to make list items `<li>` tags generally and test to see if the child `<a>` tag works well. The divider changing its element based on the context is actually a bit tricky. I will think about it!

**Comment by aforemny** [comment]
I removed `Lists.listItem` and added `Lists.groupDivider` to be `<hr>`. I added the separator role to `Lists.divider` (5f6535db7b319bb08588552afa86442b172948de). Thank you for your help!
