### ISSUE TITLE
Package docs unavailable?

### ISSUE THREAD

**Issue by akavel** [aforemny/elm-mdc#59]
I've just stumbled upon this project in search for a UI package for Elm; the Readme seems to link to http://package.elm-lang.org/packages/aforemny/elm-mdc/latest as the package docs, but the link seems to 404 for me; is it the correct link? Sorry if I misunderstood something, I'm a total newbie to Elm...

**Comment by aforemny** [comment]
I uploaded the [docs.json of current master](https://gist.github.com/aforemny/51de70f3c30506252e3253473a16d4dd) if you want to have a look.

**Comment by aforemny** [comment]
See #80. Thanks for reporting it!
