### ISSUE TITLE
Make elm-mdc.js compatible with Elm.Main.embed

### ISSUE THREAD

**Issue by berenddeboer** [aforemny/elm-mdc#61]
I'm seeing:

`TypeError: Argument 1 of MutationObserver.observe is not an object. elm-mdc.js:1:5421 `

in My FireFox (nightly) console. Not sure what this is or if this is important, but just logging here.

**Comment by berenddeboer** [comment]
This is the elm-mdc.js generated with `make`.

Where are the examples? Don't see such a directory.

**Comment by berenddeboer** [comment]
Ah, just created :-)

**Comment by aforemny** [comment]
I am not seeing that warning if I run the hello-world example in Mozilla Firefox 57.0.4.

**Comment by berenddeboer** [comment]
Me too. That's fine. But I still get it in my app! Even when loading the hello-world `elm-mdc.js`.

Yes, I have my own `index.html`. But looks very similar to yours I think.

**Comment by berenddeboer** [comment]
Found it, I as using:

    var node = document.getElementById('main');
    var app = Elm.Main.embed(node);

with full screen this disappears. Switching to full screen, that's what I want anyway, and I didn't know about that call, thanks!

**Comment by aforemny** [comment]
OK. I will leave this open as elm-mdc should be compatible with embed use. Thanks for reporting!

**Comment by berenddeboer** [comment]
BTW, now things start working! I was struggling to see why the drawer didn't open, but now it does. Brilliant.

PS: as this is a new app, would like to use latest, so will see if I can implement TopAppBar support. Unless this is something you can do real quick and have time for now :-)

**Comment by aforemny** [comment]
It seems MDC Web got a big update around version 0.35.0, this library currently implements 0.30.0. It seems TopAppBar was named Toolbar before, so check out `Material.Toolbar` before you start implementing something.

I will not have time to update this library to 0.35.0 in the immediate future.

**Comment by aforemny** [comment]
Hi @berenddeboer, would you happen to still have an example demonstrating that something does not work using `Elm.Main.embed()`? I am currently testing the demo, and I cannot seem to reproduce it. (I updated the live demo to show the embed branch if that helps.)

**Comment by berenddeboer** [comment]
Cannot reproduce this either.

**Comment by vikrem** [comment]
I've just ran into this.

The issue is caused by including the js sources in the `head` tag, such as in the installation docs in the README.

Moving the `<script>` tags to the body of the html instead (as is in the hello-world example), causes this error to go away.

**Comment by SidneyNemzer** [comment]
Nice catch @vikrem. Based on the error @berenddeboer mentioned in the issue description, I think it's coming from this line:

https://github.com/aforemny/elm-mdc/blob/99b7a56a25e836407e9715e593e11bed9d0c4b0f/src/elm-mdc.js#L161

Because `document.body` will be `null` (or `undefined`?) if the script runs in the `head`.

**Comment by berenddeboer** [comment]
Indeed, I actually always have the javascript in the body.
