### ISSUE TITLE
Drawer html does not use the <nav> + <a> structure from the official examples

### ISSUE THREAD

**Issue by berenddeboer** [aforemny/elm-mdc#62]
The official documentation says drawers have a nav inside them for the items:

````<aside class="mdc-drawer mdc-drawer--temporary mdc-typography">
  <nav class="mdc-drawer__drawer">
    <header class="mdc-drawer__header">
      <div class="mdc-drawer__header-content">
        Header here
      </div>
    </header>
    <nav id="icon-with-text-demo" class="mdc-drawer__content mdc-list">
      <a class="mdc-list-item mdc-list-item--activated" href="#">
        <i class="material-icons mdc-list-item__graphic" aria-hidden="true">inbox</i>Inbox
      </a>
      <a class="mdc-list-item" href="#">
        <i class="material-icons mdc-list-item__graphic" aria-hidden="true">star</i>Star
      </a>
    </nav>
  </nav>
</aside>
````

However the examples use a list, generating quite different (and styled) output. What would be the best way to fix this? I probably can generate the html myself and get that in there instead of the Lists.ul, but shouldn't there be some kind of support to make this easier?

**Comment by aforemny** [comment]
Maybe this is related to elm-mdc implementing MDC Web v0.30.0 instead of v0.35.1. See my comment in #61.

**Comment by berenddeboer** [comment]
Have created a pull request for this: https://github.com/aforemny/elm-mdc/pull/64
