### ISSUE TITLE
Textfield.label is required, else you can't type input, is that by design?

### ISSUE THREAD

**Issue by berenddeboer** [aforemny/elm-mdc#72]
If you don't specify Textfield.label as an option for Material.Textfield.view, you can't type in the field.

Is that on purpose? Or an mdc issue?

Specifying an empty string works, but just surprised this was needed, as I have a case where I don't want any label.

**Comment by aforemny** [comment]
> If you don't specify Textfield.label as an option for Material.Textfield.view, you can't type in the field.

That sounds like an issue in elm-mdc. It is not on prupose, and I think you should be able to have a text-field without a label.

**Comment by aforemny** [comment]
Hi @berenddeboer, I just checked in current master and Textfields without `Textfield.label` work just fine.
