### ISSUE TITLE
Change `Materal.Index` to String

### ISSUE THREAD

**Issue by aforemny** [aforemny/elm-mdc#79]
Hi,
I am thinking that I would like to make function signatures look like this:

```
Button.view Mdc "globally-unique-id" model.mdc
```

rather than

```
Button.view Mdc [1,2,3] model.mdc
```

I will make this switch at some point, thought I will announce it before. I think this is the obvious choice for indices right now. Feedback is welcome!

**Comment by aforemny** [comment]
b390b5a11681ca55bb7bba6db6fa2e5dfa7ec02b Use string ids in demo
00d49856b93a13f5d121352eb558b0e5120fa5c7 Make Material.Index a String

**Comment by berenddeboer** [comment]
I'm much in favour. We can then use this id and insert that into the html at the right spots too, this makes it much easier for external tools (like behat) to interact with the page.

**Comment by aforemny** [comment]
This is in master now (1d342ea4e2b28a8d4e27098a96fa33b360a2b4d9, 3c7c18e8c222b5ef2c6be684737f82bba0cf5eeb). Please share any feedback migrating.

**Comment by berenddeboer** [comment]
It should emit the id to the "id" attribute of the native control, and to the "for" attribute for the label IMO. I need an id on the native control to make BDD work, i.e. without id it's hard for external programs to interact with elm-mdc programs. You can't use label for example as the for attribute isn't set.
