### ISSUE TITLE
404 for package documentation

### ISSUE THREAD

**Issue by kolloch** [aforemny/elm-mdc#80]
Maybe expected but currently the package documentation link is broken.

**Comment by SidneyNemzer** [comment]
See #59 🙂

**Comment by aforemny** [comment]
I updated the README.md to be less confusing about that, hopefully: 0d018631127b05c2bf793974be891e0542ef2655. Thank you very much for reporting this!

**Comment by kolloch** [comment]
:) sorry for the duplicate!
