### ISSUE TITLE
Question on how to use this.

### ISSUE THREAD

**Issue by thitemple** [aforemny/elm-mdc#83]
Hi, I'm trying to use this but I'm able to make it work. I installed it using elm-github-install so now my elm-package.json file has this entry `"aforemny/elm-mdc": "git@github.com:aforemny/elm-mdc.git"`

I downloaded the file elm-mdc.js and added to index.html.

I'm using create-elm-app to build the application, but I have ejected from it so I can build sass files, when I try to start the application I'm seeing this error: 

```
/src/Main.elm
Module build failed: Error: Compiler process exited with error Compilation failed
Error in $: Ran into invalid constraint "git@github.com:aforemny/elm-mdc.git" for aforemny/elm-mdc

It should look something like "1.2.1 <= v < 2.0.0", with no extra or missing
spaces. The middle letter needs to be a 'v' as well.
```

Can you help me with this?

**Comment by SidneyNemzer** [comment]
Since you're using elm-github-install, your elm-package.json should look like this:

```
{
  ...
  "dependencies": {
    "aforemny/elm-mdc": "1.0.0 <= v < 2.0.0"
  }
  "dependency-sources": {
    "aforemny/elm-mdc": {
      "url": "https://github.com/aforemny/elm-mdc",
      "ref": "0d018631127b05c2bf793974be891e0542ef2655"
    }
  }
  ...  
}
```

The "ref" value should be a tree-like reference, so a SHA1 or Git tag should work. The ref is optional, but I'd recommend specifying it, otherwise you'd get the mater at the time you install packages. The ref above is the SHA1 of the master branch right now -- there are no tags in this repo yet, otherwise I'd use the latest version tag.

**Comment by thitemple** [comment]
@SidneyNemzer Thanks for your answer, can this be installed without elm-github-install? By your answer I thought it was implied it can. I'd prefer to use the regular `elm package`

**Comment by SidneyNemzer** [comment]
Unfortuantly, this package can't be installed with elm-package, since it's not published on http://package.elm-lang.org/, I believe elm-github-install is the only option for now

Perhaps @aforemny can provide a rough timeline, or the tasks that need to be completed before publishing?

**Comment by deiga** [comment]
@aforemny Are you considering publishing this package to http://package.elm-lang.org ? With Elm 0.19 it's impossible to use the github installer
