### ISSUE TITLE
Navigating without closing menu disables vertical scroll

### ISSUE THREAD

**Issue by fdbeirao** [aforemny/elm-mdc#87]
Steps to reproduce:

Tested in `Google Chrome Version 67.0.3396.62 (Official Build) (64-bit)`
Tested in `Microsoft Edge 42.17134.1.0`

1) Go to https://aforemny.github.io/elm-mdc/#
2) See that the page is vertically scrollable;
3) Click the `Menu (Pop over menus)` option;
4) Click the `SHOW MENU` purple button;
5) Click the arrow on the top left of the page to navigate back (the trick is to not close the menu!);
6) See that the page is no longer vertically scrollable;

I am not sure if this issue only affects the demo page, as I am not currently using elm-mdc for any project.

Cheers

**Comment by aforemny** [comment]
Hi @fdbeirao, thank you for reporting this! I will look into that.

**Comment by aforemny** [comment]
This issue should be fixed in d320672318d5ced533d3b928855c49865ab27271.

**Comment by aforemny** [comment]
This issue should be fixed in d320672318d5ced533d3b928855c49865ab27271.
