### ISSUE TITLE
Handling onFocus on Textfield

### ISSUE THREAD

**Issue by berenddeboer** [aforemny/elm-mdc#88]
It appears I cannot supply my own Options.onFocus for a Textfield is that right? Is that something that can be fixed?

I had a bit of a look at the source code and it doesn't appear that easy, at least not for me. Implementation.elm sets its own onFocus, and I suppose Elm doesn't handle multiple onFocus handlers. So it looks like in the update function you would need to check if the user has set an onFocus and chain that somehow.

**Comment by aforemny** [comment]
Hi @berenddeboer, it should be possible to set your own `Options.onFocus` handler for a Textfield. Since the focus element does not bubble?, you would have to set it on `Textfield.nativeControl`.

**Comment by berenddeboer** [comment]
Working!

I suppose this is "just an elm thing" :-) But would love to see this discussed in the docs as I think there will be more people like me whose first exposure to Elm is through elm-mdc.

**Comment by aforemny** [comment]
Glad it is working! :) I will keep this open until I updated the documentation.

**Comment by aforemny** [comment]
I addressed this in ccc0c54d1e4675e78cb5bfd63edbf29302f03ce1.
