### ISSUE TITLE
Slider steps not per step I think

### ISSUE THREAD

**Issue by berenddeboer** [aforemny/elm-mdc#93]
Steps with discrete works fine.

But IMO there are two issues:

1. Steps should be a float (I have a float slider with steps of 0.25).  [From the docs](https://material.io/develop/web/components/input-controls/sliders/)

> MDCSlider supports quantization by allowing users to supply a floating-point step value via a data-step attribute.

2. Steps should work without the slider having to be discrete as I understand it [from the docs](https://material.io/develop/web/components/input-controls/sliders/):

> NOTE: If a slider contains a step value it does not mean that the slider is a “discrete” slider. “Discrete slider” is a UX treatment, while having a step value is behavioral.

If you agree, I might submit a fix.

**Comment by aforemny** [comment]
@berenddeboer Great catch! I agree.

**Comment by aforemny** [comment]
Fixed in #97. Thank you @berenddeboer!
