### ISSUE TITLE
Make it easier to provide the autocomplete attribute

### ISSUE THREAD

**Issue by berenddeboer** [aforemny/elm-mdc#96]
Setting the autocomplete attribute is a fair amount of code:

    Textfield.nativeControl [ Options.attribute (Html.Attributes.attribute "autocomplete" "email") ]

Can I submit a patch to make this easier by adding an autocomplete attribute like "aria"?

**Comment by aforemny** [comment]
Yes. Please do. You can add it to Textfield directly, because I think this is the only place where you would want to use it. Just make your definition a function `autocomplete : String -> Property m`.

**Comment by aforemny** [comment]
PS. Do you have documentation about the autocomplete attribute? I cannot seem to find a good reference. What are the allowed values (I am only finding "on", "off"), where can you set it on (I am finding <form>)?

**Comment by berenddeboer** [comment]
on/off is old, here is [the complete list](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill).

**Comment by aforemny** [comment]
Thank you! It seems that the only controls this is relevant for are `<input>`, `<textarea>` and `<select>`, so I would prefer this to be exposed as `Textfield.autocomplete` and `Select.autocomplete` if appropriate, ie. if MDC Web text-field and select components are compatible with this attribute.

**Comment by aforemny** [comment]
I would not mind exposing `Options.autocomplete` as well and make `Textfield.autocomplete` and `Select.autocomplete` specializations of that (wrapping in `nativeControl`).

**Comment by aforemny** [comment]
c60e73961b8ab6be5d93fe65525484b2fe65fc3b

**Comment by aforemny** [comment]
c60e73961b8ab6be5d93fe65525484b2fe65fc3b

**Comment by berenddeboer** [comment]
Just coming back to this, it would be nice to have the list type safe. How do we do that? I.e.

type AutoFill 
  = Email 
  | Username

On the other hand [more complex values are possible](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill), such as autocomplete="section-blue shipping street-address", which would be harder.

Or maybe more simple like:

```elm
Textfield.autocomplete AutoFill.email
````

where:

```elm
module AutoFill exposing (..)

email = "email"
````
